version: 2

models:
  - name: dim_log
    columns:
      - name: 
        tests:
          - 
      - name: 
        description: 
        tests:
          - 
      - name: 
        tests:
          - 

  - name: dim_membership
    columns:
      - name: 
        tests:
          - 
          - 
      - name: 
        tests:
          - 
      - name: 
        tests:
          - 

  - name: dim_transaction
    columns:
      - name: membership_id
        tests:
          - not_null
      - name: charge_amount
        tests:
          - not_null
      - name: currency
        tests:
          - not_null
      - name: description_event
        tests:
          - not_null
      - name: status
        tests:
          - not_null
      - name: message
        tests:
          - not_null
      - name: transaction_date
        tests:
          - not_null
      - name: triggered_by
        tests:
          - not_null
      - name: payment_method
        tests:
          - not_null
